<?php
/**
 *
 * @link https://github.com/oakensoul/application-skeleton for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package application-skeleton
 */
?>

<div class="container">
	<div class="starter-template">
		<h1>Data Modeling</h1>
		<p class="lead">
			Some sort of witty description here<br>
			Some more descriptive test here too when I get there...
		</p>
	</div>
</div>